### ISSUE TITLE
SocketException: connection reset

### ISSUE THREAD

**Issue by quinao** [mailjet/mailjet-apiv3-java#108]
Hello,

I'm using mailjet java client to manage my contacts on mailjet.
When trying to read information about an email, a "SocketException: connection reset" is thrown.

Here's the code trhowing the error:

`MailjetRequest contact = new MailjetRequest(Contact.resource, email);`
`MailjetResponse response = client.get(contact);`

Here's the stacktrace:

> com.turbomanage.httpclient.HttpRequestException: java.net.SocketException: Connection reset
	at com.turbomanage.httpclient.AbstractHttpClient.doHttpMethod(AbstractHttpClient.java:236)
	at com.turbomanage.httpclient.AbstractHttpClient.execute(AbstractHttpClient.java:173)
	at com.turbomanage.httpclient.AbstractHttpClient.get(AbstractHttpClient.java:103)
	at com.mailjet.client.MailjetClient.get(MailjetClient.java:169)
	at com.axelor.apps.administration.mailjet.MailjetService.requestContactId(MailjetService.java:103)
	(...)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at com.turbomanage.httpclient.AbstractHttpClient.doHttpMethod(AbstractHttpClient.java:214)

Can you explain to me what it means and how to fix it please?

Thanks,

quinao

**Comment by todorDim** [comment]
Hey @quinao,

We'll take a closer look and get back to you.

Regards,
T.

**Comment by quinao** [comment]
Hello again,

I solved my problem : I used to instantiate the MailjetClient some time before actually sending an request, so my guess is that Mailjet server closed the connection for being innactive.
Now I instantiate the client jsut before sending a request and it works fine.

**Comment by todorDim** [comment]
Hi @quinao 

Glad to hear it !

Regards,
T.

**Comment by abambova** [comment]
Closing this issue as it has been solved. Please feel free to post a new issue if needed.

**Comment by nseb** [comment]
@todorDim  , Hello , why client keep connection open ? 
The problem when you don't have a lot of email, the socket closes, without you knowing.
Isn't there a method to verify that the client is up before calling without meeting each time?
