### ISSUE TITLE
Google Cloud Functions MailjetUnauthorizedException

### ISSUE THREAD

**Issue by AlexSheva-mason** [mailjet/mailjet-apiv3-java#152]
I'm trying to run MailJet Api within the google cloud function (written in Kotlin) and keep having MailjetUnauthorizedException or "Invalid APi key" responses. I was following "Send your first email" on the mailjet website, but later tried following guide here - both with no success.
Gradle dependency:
``` //MailJet api
    implementation("com.mailjet:mailjet-client:5.1.1") 
```
My code:
```
private val options = ClientOptions.builder()
        .apiKey(System.getenv("_my_valid_api_key_here_"))
        .apiSecretKey(System.getenv("_my_valid_secret_key_here_"))
        .build()
    private val client: MailjetClient = MailjetClient(options)

    fun sendReportEmail(reportMessage: String) {
        val request = MailjetRequest(Emailv31.resource)
            .property(
                Emailv31.MESSAGES, JSONArray()
                    .put(
                        JSONObject()
                            .put(
                                Emailv31.Message.FROM, JSONObject()
                                    .put("Email", "_my_valid_email_from_Sender domains & addresses_")
                                    .put("Name", "Alexei")
                            )
                            .put(
                                Emailv31.Message.TO, JSONArray()
                                    .put(
                                        JSONObject()
                                            .put("Email", "_my_valid_email_from_Sender domains & addresses_")
                                            .put("Name", "Alexei")
                                    )
                            )
                            .put(Emailv31.Message.SUBJECT, "Greetings from Mailjet.")
                            .put(Emailv31.Message.TEXTPART, "My first Mailjet email")
                            .put(
                                Emailv31.Message.HTMLPART,
                                "<h3>Dear passenger 1, welcome to <a href='https://www.mailjet.com/'>Mailjet</a>!</h3><br />May the delivery force be with you!"
                            )
                            .put(Emailv31.Message.CUSTOMID, "AppGettingStartedTest")
                    )
            )
        val response = client.post(request)
        println(response.status)
        println(response.data)
    }
```

Exception:
``` 
com.mailjet.client.errors.MailjetUnauthorizedException: To do a request to MailJet api, api key and api secret should be set
	at com.mailjet.client.MailjetClient.getPreconfiguredRequestBuilder(MailjetClient.java:205)
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:114)
	at com.shevaalex.function.mail.MailManager.sendReportEmail(MailManager.kt:60)
	at com.shevaalex.function.MainFunction.service(MainFunction.kt:28)
	at com.google.cloud.functions.invoker.NewHttpFunctionExecutor.service(NewHttpFunctionExecutor.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.google.cloud.functions.invoker.runner.Invoker$NotFoundHandler.handle(Invoker.java:450)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

When I was running previous versions of mailjet client (4.2.0) I was getting something like "invalid api key" error within the response

**Comment by goacoustic** [comment]
Hi @AlexSheva-mason, thanks for opening the issue!

You can pass your access credentials directly, without reading them from environment variables, like

```java
.apiKey("_your_valid_api_key_here_")
.etc
```

or, you can pass it through env variables in your cloud function:
```java
.apiKey(System.getenv("MJ_API_KEY"))
.etc
```
and in [cloud function configuration](https://cloud.google.com/functions/docs/env-var) you have set up variable value like MJ_API_KEY=_your_valid_api_key_

hope this helps!

**Comment by AlexSheva-mason** [comment]
Thank you! This does appear to be working indeed
```
.apiKey("_your_valid_api_key_here_")
.etc
```
Sorry for opening an issue that wasn't really an issue (some confusion on the website's "Send your first email" section does exist though)
