### ISSUE TITLE
SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by TnCoders** [mailjet/mailjet-apiv3-java#157]
Hello I'am having This error when i try to send email

**com.mailjet.client.errors.MailjetClientCommunicationException: Connection Exception**
at com.mailjet.client.MailjetClient.post(MailjetClient.java:123)
at com.mailjet.client.transactional.SendEmailsRequest.sendWith(SendEmailsRequest.java:61)
...
...
**Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake**
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:994)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:336)
at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
at okhttp3.RealCall.execute(RealCall.java:81)
at com.mailjet.client.MailjetClient.post(MailjetClient.java:118)
... 53 more
**Caused by: java.io.EOFException: SSL peer shut down incorrectly**
at sun.security.ssl.InputRecord.read(InputRecord.java:505)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
... 77 more

I'm using
**Mailjet 5.1.1
Spring Boot 2.4.3**

This Spring App is Dockerized using:

**FROM openjdk:8-jdk-alpine** 

**This is how i create the mailjet Client:**

```
ClientOptions options = ClientOptions.builder().apiKey(env.getProperty("MJ_APIKEY_PUBLIC"))
.apiSecretKey(env.getProperty("MJ_APIKEY_PRIVATE")).build();

MailjetClient client = new MailjetClient(options);
```

the Other code is like the exemple on the documentation here.

**EDIT:** 
-----------------------

I tested from my Infra to nmap this is the result : 

-----------------------
/var/www/html# **_nmap --script ssl-enum-ciphers -p 443 in-v3.mailjet.com_**
Starting Nmap 7.70 ( https://nmap.org ) at 2021-03-24 10:47 UTC
Nmap scan report for in-v3.mailjet.com (104.199.96.85)
Host is up (0.0014s latency).
rDNS record for 104.199.**.**: 85.96.***.***.bc.googleusercontent.com

PORT    STATE SERVICE
443/tcp open  https

Nmap done: 1 IP address (1 host up) scanned in 6.98 seconds
---------------------

Another Try on api.mailjet
----------------- 
**nmap --script ssl-enum-ciphers -p 443 api.mailjet.com**
Starting Nmap 7.70 ( https://nmap.org ) at 2021-03-24 11:03 UTC
Nmap scan report for api.mailjet.com (35.187.79.8)
Host is up (0.0016s latency).
rDNS record for ** ********: *********.bc.googleusercontent.com

PORT    STATE SERVICE
443/tcp open  https

Nmap done: 1 IP address (1 host up) scanned in 6.41 seconds

------------------

No ssl-enum-ciphers: TLSv1.0 + ..... in the response.

What Do you Think ?

**Comment by TnCoders** [comment]
It apear It was Infra Probleme Solved

**Comment by anil774484** [comment]
Hello TnCoders, we are also facing the same issue  with Mailjet. We update TLS version from 1.3 to 1.2. still we are facing the handshake error and session is shutting down
