### ISSUE TITLE
java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto([B[BIII)[B

### ISSUE THREAD

**Issue by xehpuk** [mailjet/mailjet-apiv3-java#184]
Using 5.2.2:

```
java.lang.NoSuchMethodError: kotlin.collections.ArraysKt.copyInto([B[BIII)[B
	at okio.Segment.writeTo(Segment.kt:169)
	at okio.Segment.compact(Segment.kt:152)
	at okio.Buffer.write(Buffer.kt:1491)
	at okio.Buffer.read(Buffer.kt:1503)
	at okio.Buffer.writeAll(Buffer.kt:1290)
	at okio.Options$Companion.buildTrieRecursive(Options.kt:189)
	at okio.Options$Companion.buildTrieRecursive(Options.kt:175)
	at okio.Options$Companion.buildTrieRecursive$default(Options.kt:107)
	at okio.Options$Companion.of(Options.kt:72)
	at okhttp3.internal.Util.<clinit>(Util.kt:70)
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471)
	at com.mailjet.client.MailjetClient.createDefaultOkHttpClient(MailjetClient.java:299)
	at com.mailjet.client.MailjetClient.<init>(MailjetClient.java:78)
```

Related to #174?

**Comment by vitalii-chornobryvyi-swi** [comment]
@xehpuk, thanks for raising this issue!
Sorry for the late reply.
Can you please double-check with 5.2.3 release since there was also an update of a dependency version? And then reply if it resolved the issue.

**Comment by xehpuk** [comment]
It's apparent from the stack trace that this has nothing to do with `org.json`.
It is a problem with `okhttp`, and I "fixed" it by adding a dependency to `org.jetbrains.kotlin:kotlin-stdlib:1.5.31`.

**Comment by vitalii-chornobryvyi-swi** [comment]
So we can assume that your problem is solved and the issue can be closed?

**Comment by xehpuk** [comment]
I added a workaround in my project. The problem of your project is not solved, no.

**Comment by vitalii-chornobryvyi-swi** [comment]
To some extent, I agree with you. However, there are certain buts. The client itself does not use the org.jetbrains.kotli library, since it does not need it for correct operation. In this case, adding the library mentioned above is an integration for the specific implementation. 
Probably will be reviewed in future releases

**Comment by xehpuk** [comment]
Can you please clarify what you meant by "specific implementation" and how I could use the library without adding `kotlin-stdlib` to my dependencies?
