### ISSUE TITLE
delete customer 401 Unauthorized

### ISSUE THREAD

**Issue by lrkwz** [mailjet/mailjet-apiv3-java#213]
When I perform a delete customer I always receive a 401 code.

The `client` is initialized the "standard" way:

```java
final ClientOptions options = ClientOptions.builder()
                .apiKey(apiKey)
                .apiSecretKey(apiSecretKey)
                .build();
        final MailjetClient client = new MailjetClient(options);
```

Example given a function that returns the customer ID (assuring he/she exists)
```java
    @Test
    public void removeContact() throws MailjetException {
        final MailjetRequest request = new MailjetRequest(Contact.resource, getContactIdByEmail("luca.orlandi@gmail.com"));
        final MailjetResponse response = client.delete(request);
        assertThat(response.getStatus()).isEqualTo(200);
    }
```
output is:
```
com.mailjet.client.errors.MailjetUnauthorizedException: Unauthorized. Please,verify your access key and access secret key or token for the given account

	at com.mailjet.client.MailjetResponseUtil.validateMailjetResponse(MailjetResponseUtil.java:32)
	at com.mailjet.client.MailjetClient.parseResponse(MailjetClient.java:297)
	at com.mailjet.client.MailjetClient.delete(MailjetClient.java:240)
	at learning.MailJetApiTest.removeContact(MailJetApiTest.java:145)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

Same if I use a filter such as:

```java
    @Test
    public void removeContactByMail() throws MailjetException {
        final MailjetRequest request = new MailjetRequest(Contact.resource)
                .filter(Contact.EMAIL, "luca.orlandi@gmail.com");
        final MailjetResponse response = client.delete(request);
        assertThat(response.getStatus()).isEqualTo(200);
    }
```

**Comment by lrkwz** [comment]
I tried with `OkHttpClient`, no 404 error but still no luck, my contact is still there and the following test fails

```java
    @Test
    public void removeContactByID() throws IOException, MailjetException {
        final String randomName = generateRandomUsername();
        final int contactID = addContact(randomName, randomName + "@example.com");

        final String base64Credentials = Base64.getEncoder().encodeToString((API_KEY + ":" + API_SECRET_KEY).getBytes());

        final OkHttpClient httpClient = new OkHttpClient();
        final Request request = new Request.Builder()
                .url("https://api.mailjet.com/v4/contacts/" + contactID)
                .addHeader("authorization", "Basic " + base64Credentials)
                .delete()
                .build();
        try (final Response response = httpClient.newCall(request).execute()) {
            assertThat(response.isSuccessful()).isTrue();
        }

        final Integer id = getContactIdByEmail(randomName + "@example.com");
        assertThat(id).isNull();
    }
```

**Comment by mdmytrash** [comment]
Hello @lrkwz. Thank you for reaching out. Is the question still relevant?

**Comment by mdmytrash** [comment]
Hello @lrkwz . 
We will close this issue because it may be a temporary problem, and we haven't received a response from you.

Please feel free to reopen this issue in case you need any more help.

**Comment by lrkwz** [comment]
Sorry I didn't have chance to test it again. Thank you.

*=> Luca <http://stackexchange.com/users/239746>*
PEC: ***@***.*** https://t.me/lrkwz



Il ven 5 set 2025, 23:03 mdmytrash ***@***.***> ha scritto:
