### ISSUE TITLE
update customer by ID 404

### ISSUE THREAD

**Issue by lrkwz** [mailjet/mailjet-apiv3-java#214]
Updateing by userId fails with 404

```java
    @Test
    public void updateContact() throws MailjetException {
        final String randomName = generateRandomUsername();

        final int contactID = addContact(randomName, randomName + "@example.com");
        assertThat(contactID).isGreaterThan(0);

        final MailjetRequest request = new MailjetRequest(Contact.resource, contactID)
                .setBody(new HashMap<>(Map.of("Name", "Mario Rossi")));
        final MailjetResponse response = client.put(request);
        assertThat(response.getStatus()).isEqualTo(200);
    }
```

returns

```
com.mailjet.client.errors.MailjetClientRequestException: { "ErrorInfo" : "", "ErrorMessage" : "Object not found", "StatusCode" : 404 }

	at com.mailjet.client.MailjetResponseUtil.validateMailjetResponse(MailjetResponseUtil.java:37)
	at com.mailjet.client.MailjetClient.parseResponse(MailjetClient.java:297)
	at com.mailjet.client.MailjetClient.put(MailjetClient.java:192)
	at learning.MailJetApiTest.updateContactById(MailJetApiTest.java:237)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by mdmytrash** [comment]
We closed this issue because we haven't gotten a response from you for a long time. 
In case of any issues, feel free to reopen this issue or create a new one.
