### ISSUE TITLE
Create newsletter

### ISSUE THREAD

**Issue by sicoa** [mailjet/mailjet-apiv3-java#53]
Hello there
i have encountered another issue. I will explain:
I have been unsuccessful in creating a Newsletter in this way, with fixed values. Maybe i am doing something awfully wrong. Any insight will be greatly appreciated:
 
```java
MailjetRequest request;
					MailjetResponse response = null;
					request = new MailjetRequest(Newsletter.resource)
					            .property(Newsletter.CONTACTSLIST, 1)
					            .property(Newsletter.LOCALE, "en-US")
					            .property(Newsletter.SENDER, "ovSPITItest")
		                                    .property(Newsletter.SENDEREMAIL, "__@sicoa.com");

response = cl.post(request);
```
The request:
```
{"Filters":"{}","Action ID":0,"Resource":"newsletter","ID":0,"Body":"{\"Locale\":\"en-US\",\"Sender\":\"ovSPITItest\",\"SenderEmail\":\"ov@sicoa.com\",\"ContactsList\":1}"}
````
The errors when executing
response = cl.post(request); :
```
java.net.UnknownHostException: api.mailjet.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at com.turbomanage.httpclient.HttpResponse.<init>(HttpResponse.java:22)
	at com.turbomanage.httpclient.AbstractHttpClient.readErrorStream(AbstractHttpClient.java:360)
	at com.turbomanage.httpclient.AbstractHttpClient.doHttpMethod(AbstractHttpClient.java:227)
	at com.turbomanage.httpclient.AbstractHttpClient.execute(AbstractHttpClient.java:173)
	at com.turbomanage.httpclient.AbstractHttpClient.post(AbstractHttpClient.java:130)
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:154)
	at com.sicoa.mailjet.rest.NewsletterClass.newsletterCreate(NewsletterClass.java:365)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
BasicRequestHandler.onError got
com.turbomanage.httpclient.HttpRequestException: java.net.UnknownHostException: api.mailjet.com
	at com.turbomanage.httpclient.AbstractHttpClient.doHttpMethod(AbstractHttpClient.java:236)
	at com.turbomanage.httpclient.AbstractHttpClient.execute(AbstractHttpClient.java:173)
	at com.turbomanage.httpclient.AbstractHttpClient.post(AbstractHttpClient.java:130)
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:154)
	at com.sicoa.mailjet.rest.NewsletterClass.newsletterCreate(NewsletterClass.java:365)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.UnknownHostException: api.mailjet.com
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	at com.turbomanage.httpclient.AbstractHttpClient.doHttpMethod(AbstractHttpClient.java:214)
	... 50 more
```

**Comment by GuillaumeBadi** [comment]
Hey @sicoa !

2 things happen here! First of all you need to include all the [mandatory properties](http://dev.mailjet.com/email-api/v3/newsletter/).

And 'en-US' is 'en_US' ;)

**Comment by sicoa** [comment]
Oh yes you are right and thank you for the answer on my lack of point Guillaume
i tested this time with wrong values (en_US and needs a subject)
i have changed it (in my official tests those were correct :) ) but still i can reproduce the 
issue found through my previous implementation.

```java
MailjetRequest request;
MailjetResponse response = null;
request = new MailjetRequest(Newsletter.resource)
                                .property(Newsletter.CONTACTSLIST, 1)
                                .property(Newsletter.LOCALE, "en-US")
                                .property(Newsletter.SENDER, "ovSPITItest")
                                .property(Newsletter.SENDEREMAIL, "__@sicoa.com");
                                .property(Newsletter.SUBJECT, "ASUBJECT");

response = cl.post(request);
```
Request:
```
{"Filters":"{}","Action ID":0,"Resource":"newsletter","ID":0,"Body":"{\"Locale\":\"en_US\",\"Sender\":\"ovSPITItest\",\"SenderEmail\":\"ov@sicoa.com\",\"Subject\":\"ASUBJECT\",\"ContactsList\":1}"}
```
Response:
```
{"Status":400,"ErrorInfo":"","ErrorMessage":"Invalid json input: expected \",\", but found \"1\" at stream position 107 ...ctsList\":1|}...","StatusCode":400}
```

Trying it without the library with httpclient and credentials etc
suplying the json below with the mandatory fields i get the exact same response as above
```
{
	"Locale": "en-US",
	"Sender": "ovSPITItest",
	"SenderEmail": "ov@sicoa.com",
	"Subject": "ASUBJECT",
	"ContactsList": 1
}
```
So i am led to believe that this can only be a matter of the JSON sent. What am i doing wrong?
Thank you very much once again

**Comment by sicoa** [comment]
Oh yes you are right and thank you for the answer on my lack of point Guillaume
i tested this time with wrong values (en_US and needs a subject)
i have changed it (in my official tests those were correct :) ) but still i can reproduce the
issue found through my previous implementation.
```java
MailjetRequest request;
MailjetResponse response = null;
request = new MailjetRequest(Newsletter.resource)
                                .property(Newsletter.CONTACTSLIST, 1)
                                .property(Newsletter.LOCALE, "en-US")
                                .property(Newsletter.SENDER, "ovSPITItest")
                                .property(Newsletter.SENDEREMAIL, "__@sicoa.com");
                                .property(Newsletter.SUBJECT, "ASUBJECT");

response = cl.post(request);
```
Request:
```
{"Filters":"{}","Action ID":0,"Resource":"newsletter","ID":0,"Body":"{\"Locale\":\"en_US\",\"Sender\":\"ovSPITItest\",\"SenderEmail\":\"ov@sicoa.com\",\"Subject\":\"ASUBJECT\",\"ContactsList\":1}"}
```
Response:
```
{"Status":400,"ErrorInfo":"","ErrorMessage":"Invalid json input: expected \",\", but found \"1\" at stream position 107 ...ctsList\":1|}...","StatusCode":400}
```
Trying it without the library with httpclient and credentials etc
suplying the json below with the mandatory fields i get the exact same response as above
```
{
    "Locale": "en-US",
    "Sender": "ovSPITItest",
    "SenderEmail": "ov@sicoa.com",
    "Subject": "ASUBJECT",
    "ContactsList": 1
}
```
So i am led to believe that this can only be a matter of the JSON sent. What am i doing wrong?
Thank you very much once again

**Comment by GuillaumeBadi** [comment]
Yep ! can you pull from the last push on @sicoa-fixes branch ? I have added the property helper.

Or you can just use `"ContactsListID"` instead of `Newsletter.CONTACTSLIST`

**Comment by sicoa** [comment]
The new version works fine Guillaume
This has been solved
Thank you 
Remaining yours 
sicoaDev
