### ISSUE TITLE
NPE while sending request

### ISSUE THREAD

**Issue by micbuczynski** [mailjet/mailjet-apiv3-java#72]
Hello,

Lastly I had problems with timeouts while trying to post requests. I need to get exception to retry requests or report it as failed but I only got NPE.
Its caused by trying to make json from null request in method post in MailjetClient.
```
> json = (response.getBodyAsString() != null ?
                    response.getBodyAsString() : new JSONObject().put("status", response.getStatus()).toString());
```
					
For now I have made workaround by implementing my own request handler but would be nice to get from there Exception like SocketTimeoutException or something.

Here is also stacktrace from this problem

```
BasicRequestHandler.onError got
java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.turbomanage.httpclient.HttpResponse.<init>(HttpResponse.java:22)
	at com.turbomanage.httpclient.AbstractHttpClient.readErrorStream(AbstractHttpClient.java:360)
	at com.turbomanage.httpclient.AbstractHttpClient.doHttpMethod(AbstractHttpClient.java:227)
	at com.turbomanage.httpclient.AbstractHttpClient.execute(AbstractHttpClient.java:173)
	at com.turbomanage.httpclient.AbstractHttpClient.post(AbstractHttpClient.java:130)
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:182)
	at com.comarch.telco.t3arts.agents.mailing.mailjet.test.main(test.java:33)
com.turbomanage.httpclient.HttpRequestException: java.net.SocketTimeoutException: connect timed out
	at com.turbomanage.httpclient.AbstractHttpClient.doHttpMethod(AbstractHttpClient.java:236)
	at com.turbomanage.httpclient.AbstractHttpClient.execute(AbstractHttpClient.java:173)
	at com.turbomanage.httpclient.AbstractHttpClient.post(AbstractHttpClient.java:130)
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:182)
	at com.comarch.telco.t3arts.agents.mailing.mailjet.test.main(test.java:33)
Caused by: java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:625)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153)
	at com.turbomanage.httpclient.AbstractHttpClient.doHttpMethod(AbstractHttpClient.java:214)
	... 4 more
Exception in thread "main" java.lang.NullPointerException
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:183)
	at com.comarch.telco.t3arts.agents.mailing.mailjet.test.main(test.java:33)
```

M

**Comment by GuillaumeBadi** [comment]
Hey @micbuczynski !

I don't quite understand what you are trying to achieve, How does your workaround works exactly ? Do you want me to add it ?

Guillaume

**Comment by micbuczynski** [comment]
Hi,

I just think thant its a bug and it should be fixed. 
Method post in MailjetClient class uses http-client library to make requests.

```
public MailjetResponse post(MailjetRequest request) throws MailjetException {
        
        try {
            String url = request.buildUrl();
            
            if (_debug == NOCALL_DEBUG) {
                return new MailjetResponse(new JSONObject()
                        .put("url", _baseUrl + url)
                        .put("payload", request.getBody()));
            }
            
            HttpResponse response;
            String json;
            
>>            response = _client.post(_baseUrl + url, request.getContentType(), request.getBody().getBytes("UTF8"));
            json = (response.getBodyAsString() != null ?
                    response.getBodyAsString() : new JSONObject().put("status", response.getStatus()).toString());
            return new MailjetResponse(response.getStatus(), new JSONObject(json));
        } catch (MalformedURLException ex) {
            throw new MailjetException("Internal Exception: Malformed Url");
        } catch (UnsupportedEncodingException ex) {
            throw new MailjetException("Internal Exception: Unsupported Encoding");
        }
    }
```

Problem is that response can be null and when you are trying to parse it to json it throws NPE. I think that there should be check if request is null and thow MailjetException with proper information.

Michal

**Comment by GuillaumeBadi** [comment]
I get it, I'll work on that ASAP ! Thank you for reporting this!

**Comment by GuillaumeBadi** [comment]
Hey ! Can you have a look at the last commit ? `com.mailjet.client.errors.MailjetSocketTimeoutException`

It should send an Exception when `response` is null : `MailjetSocketTimeoutException`

Guillaume

**Comment by micbuczynski** [comment]
Hello, 

This will work fine.
I found out that the reason for this error was blocking one of two IP used by mailjet. When application was trying connect to blocked IP got timeout exception.
Thanks for this fix.

Michal
