### ISSUE TITLE
Use enterprise ready http client

### ISSUE THREAD

**Issue by peterquiel** [mailjet/mailjet-apiv3-java#85]
The lib uses a http client in version 0.89 that has been written 6 years ago. 
The lib doesn't use a proper java logging facade and it is not thread safe.

The mail jet client uses the  `com.turbomanage.httpclient.BasicHttpClient` and that client uses the 
the `com.turbomanage.httpclient.BasicRequestHandler`. The comment of the `BasicRequestHandler` says:

```
 * Default {@link RequestHandler} used by {@link BasicHttpClient}. It is
 * intended to be used for simple requests with *small amounts of data* only (a
 * few kB), as it does no buffering, chunking, streaming, etc. Only character
 * set supported is UTF-8. Only {@link String} content is supported. All
 * responses are treated as {@link String}s. This class is abstract so that
 * it can be easily extended in an anonymous inner class when constructing
 * a client.
```

We use this client to send thousands of transactional mails and each mail has about 250kb of data - inline images. 

The following log messages occurs in our logs on a regular base:
```
 textPayload:  "com.turbomanage.httpclient.HttpRequestException: java.io.IOException: Error writing to server
	at com.turbomanage.httpclient.AbstractHttpClient.doHttpMethod(AbstractHttpClient.java:236)
	at com.turbomanage.httpclient.AbstractHttpClient.execute(AbstractHttpClient.java:173)
	at com.turbomanage.httpclient.AbstractHttpClient.post(AbstractHttpClient.java:130)
	at com.mailjet.client.MailjetClient.post(MailjetClient.java:210)
	at com.mailjet.client.MailjetClient$post.call(Unknown Source)
        ....
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Error writing to server
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.net.HttpURLConnection.getResponseCode(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
	at com.turbomanage.httpclient.AbstractHttpClient.writeOutputStream(AbstractHttpClient.java:304)
	at com.turbomanage.httpclient.AbstractHttpClient.doHttpMethod(AbstractHttpClient.java:217)
	... 35 more
```

I would appreciate if mail jet could offer us a more enterprise ready client.

**Comment by todorDim** [comment]
Hello @peterquiel,

Indeed your suggestion is pretty good. I'll check it out with our devs and see if we can include it in the next iteration of the wrapper.

Regards,
T.

**Comment by rafacm** [comment]
Additional to the technical issues reported above, there are also licensing issues with the  `com.turbomanage.httpclient` library since it does NOT provide a license: https://github.com/turbomanage/basic-http-client

According to https://help.github.com/en/articles/licensing-a-repository#what-happens-if-i-dont-choose-a-license:
> You're under no obligation to choose a license. However, without a license, the default copyright
> laws apply, meaning that you retain all rights to your source code and no one may reproduce,
> distribute, or create derivative works from your work.

**Comment by johnksv** [comment]
Any updates on this?
