### ISSUE TITLE
"JSONException:End of input at character 0 of" when invalid request (missing required parameters)

### ISSUE THREAD

**Issue by jderuette** [mailjet/mailjet-apiv3-java#86]
I was using API V3 (JAVA MailJet-client 4.0.5).

I try the new V3.1 (JAVA MailJet-client [4.1.1](https://mvnrepository.com/artifact/com.mailjet/mailjet-client/4.1.1)) with a very similar code (only required modifications).

I have this stack when I try top send a email : 
> JSONException:End of input at character 0 of 
> 	at org.json.JSONTokener.syntaxError(JSONTokener.java:484)
> 	at org.json.JSONTokener.nextValue(JSONTokener.java:123)
> 	at org.json.JSONObject.<init>(JSONObject.java:156)
> 	at org.json.JSONObject.<init>(JSONObject.java:175)
> 	at com.mailjet.client.MailjetClient.post(MailjetClient.java:218)
> 	at org.zeroclick.common.email.MailjetMailSender.sendEmail(MailjetMailSender.java:156)

MailjetClient.java:218 try to convert the MailJet response
`return new MailjetResponse(response.getStatus(), new JSONObject(json));`

The  json variable is an empty String, because the "response body" is empty.

This is the "header" of the response : 
> {Transfer-Encoding=[chunked], null=[HTTP/1.1 400 At least FromEmail or Sender must be provided], Date=[Thu, 29 Mar 2018 12:15:00 GMT], Content-Type=[text/html]}

The "null" parameter looks to be the "real" service response and is an error message.

This should be forwarded as an error to api-client developer ? 

The guard Line just before (l216 and 217) could consider "empty body" AND "null" response.

To get more informations, #82 should be handled in this case (the "null" header" contain useful information to understand the "400" status an could be added to the "ErrorMessage" OR "ErrorInfo" field).

**Comment by jderuette** [comment]
Is 4.2.2-SNAPSHOT of [MailjetClient.java](https://github.com/mailjet/mailjet-apiv3-java/blob/master/src/main/java/com/mailjet/client/MailjetClient.java#L175) already has a fix for this.

I think this issue can be close with the 4.2.2 release.

**Comment by jderuette** [comment]
I got this error because I was still using APi V3 when building the client (and the V3 API expected a FromEmail or Sender parameter).

Using the V3.1 API client option, allow me to send email.

new MailjetClient(user, password, **new `ClientOptions("v3.1")**);
